#
# only check on mips
#

DTRACE_ENABLE=yes

KERNCONF_MAKEOPTIONS+="DEBUG=-g"
KERNCONF_MAKEOPTIONS+="WITH_CTF=1"
KERNCONF_DEVICES+=dtrace dtraceall
WORLD_SUBDIRS_LIB+=libproc librtld_db libprocstat
WORLD_SUBDIRS_GNU_LIB+=libsupc++
WORLD_SUBDIRS_CDDL_LIB+=libctf
WORLD_SUBDIRS_CDDL_LIB+=libdtrace
WORLD_SUBDIRS_CDDL_USR_SBIN+=dtrace                                            
KERNCONF_OPTIONS+=KDTRACE_FRAME
KERNCONF_OPTIONS+=KDTRACE_HOOKS
KERNCONF_OPTIONS+=DDB_CTF

WORLD_BUILD_ENV_EXTRA+=STRIP=
WORLD_BUILD_ENV_EXTRA+=WITH_CTF=1
WORLD_BUILD_ENV_EXTRA+="CFLAGS+=\"-fno-omit-frame-pointer\""

