#!/bin/sh

# PROVIDE: ADAPTATION

. /etc/rc.subr
. /etc/network.subr

name="ADAPTATION"
start_cmd="adapt_start"
start_precmd="adapt_prestart"
start_postcmd="adapt_poststart"
stop_cmd="adapt_stop"

adapt_prestart()
{
	# Import MAC addresses with known names
	MAGIC=`dd if=/dev/flash/spi0 bs=0x10000 skip=0x7f count=1 2>/dev/null | od -tx4 -N 4 | awk '/0000000/{print $2}'`
	if [ ${MAGIC} = "35333131" ]; then
		kenv WIFI_MAC_ADDR=`dd if=/dev/flash/spi0 bs=0x10000 skip=0x7f count=1 2>/dev/null | od -j 0x0060 -N 6 -t x1 | awk '/0000140/{print $2":"$3":"$4":"$5":"$6":"$7}'`
		kenv LAN_MAC_ADDR=`dd if=/dev/flash/spi0 bs=0x10000 skip=0x7f count=1 2>/dev/null | od -j 0x0066 -N 6 -t x1 | awk '/0000146/{print $2":"$3":"$4":"$5":"$6":"$7}'`

		ifconfig are0 ether `kenv LAN_MAC_ADDR`
	fi
}

adapt_start()
{
}

adapt_poststart()
{
}

adapt_stop()
{
}

load_rc_config $name

run_rc_command $*
