#!/bin/sh

# PROVIDE: collector
# REQUIRE: MAIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

#[ -z "${collector_enable}" ] && collector_enable="YES"
collector_enable="YES"
name="collector"
command="/etc/www/${name}.sh"
rcvar=`set_rcvar`

conf_file="/etc/${name}.conf"
pidfile="/var/run/${name}.pid"

command_args="-P ${pidfile} -B ${conf_file} &"
#required_files="${conf_file}"
#required_modules="wlan_xauth wlan_wep wlan_tkip wlan_ccmp"
#extra_commands="reload"

load_rc_config ${name}
run_rc_command "$1"
