#!/bin/sh

#LOG=/tmp/DHCLIENT-SCRIPT.log
LOG=/dev/null

touch ${LOG}
echo "DHCLIENT-SCRIPT: $*" >> ${LOG}
#set >> ${LOG}
echo >>  ${LOG}

case ${reason} in
ARPSEND)
	# TODO
	;;

ARPCHECK)
	# TODO
	;;

EXPIRE)
	# TODO
	;;

PREINIT)
	# TODO
	;;

REBOOT|BOUND|RENEW)
        #interface=wan0
        #new_broadcast_address=192.168.1.255
        #new_dhcp_lease_time=3600
        #new_dhcp_message_type=5
        #new_dhcp_server_identifier=192.168.1.3
        #new_domain_name_servers='192.168.1.3 192.168.1.3'
        #new_expiry=4137
        #new_ip_address=192.168.1.5
        #new_network_number=192.168.1.0
        #new_routers=192.168.1.3
        #new_subnet_mask=255.255.255.0
        #reason=REBOOT
        ifconfig ${interface} ${new_ip_address} netmask ${new_subnet_mask}
        echo "DHCP: iface=${interface} ip=${new_ip_address} netmask=${new_subnet_mask} route=${new_routers} dns=${new_domain_name_servers}" >> ${LOG}
        query="cmd=event"
        query="${query}&state=up"
        query="${query}&iface=${interface}"
        query="${query}&gw=${new_routers}"
        query="${query}&ip=${new_ip_address}"
        query="${query}&netmask=${new_subnet_mask}"
        query="${query}&dhclient_reason=${reason}"
        query="${query}&dhclient_lease_time=${new_dhcp_lease_time}"
        query="${query}&dhclient_message_type=${new_dhcp_message_type}"
        query="${query}&dhclient_server_identifier=${new_dhcp_server_identifier}"
        query="${query}&dhclient_expiry=${new_expiry}"
        i=1
        for dns in ${new_domain_name_servers} ; do
    		query="${query}&dns${i}=${dns}"
		i=$(( ${i} + 1 ))
        done

        # Notify configuration handler
        fetch -qo - "http://127.0.0.1:8/event.xml?${query}"
	;;
*)
	;;
esac

