# TOOLS_SUBDIRS not cleaned to allow user prepend
.include <bsd.own.mk>

.CURDIR=${ZROUTER_ROOT}
SUBDIR=
SUBDIR+=tools/config
SUBDIR+=tools/packimage
.for dir in ${SUBDIR}
.warning "make dir ${MAKEOBJDIRPREFIX}/${dir}"
_DUMMY_VAR_!=mkdir -p ${MAKEOBJDIRPREFIX}/${dir}
.endfor

.include <bsd.subdir.mk>
