#!/bin/sh

# PROVIDE: FILESYSTEMS
# REQUIRE: tmp

. /etc/rc.subr

name="var"
stop_cmd=':'

load_rc_config $name


mount_md ${varsize} /var "${varmfs_flags}"


if [ -d /var/run -a -d /var/db -a -d /var/empty ] ; then
	true
elif [ -x /usr/sbin/mtree ] ; then
	/usr/sbin/mtree -deU -f /etc/mtree/BSD.var.dist -p /var > /dev/null
fi

