#!/bin/sh

# PROVIDE: watchdogd
# REQUIRE: DAEMON cleanvar
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="watchdogd"
rcvar="`set_rcvar`"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
