
#WORLD_SUBDIRS_LIB+= libcrypto libssl
#WORLD_SUBDIRS_PORTS+=/usr/ports/security/openvpn

.warning nfs_client profile used
KERNCONF_OPTIONS+=BOOTP
KERNCONF_OPTIONS+=BOOTP_NFSROOT
KERNCONF_OPTIONS+=BOOTP_NFSV3
KERNCONF_OPTIONS+=BOOTP_WIRED_TO=bfe0
KERNCONF_OPTIONS+=BOOTP_COMPAT

#KERNEL_OPTIONS+=ROOTDEVNAME=\"nfs:192.168.0.90:/usr/home/ray/Projects/MIPS/FreeBSD/rootfs-mips\"

