#!/bin/sh

CONF="/etc/upgrade.conf"

if [ -e "${CONF}" ]; then

. ${CONF}

# over write tftp server by kenv if you want.
kupgradetftp=`kenv -q zrouter.upgradetftp`
if [ -n "$kupgradetftp" ]; then
UPGRADETFTP=$kupgradetftp
fi

reroot=`kenv -q vfs.root.mountfrom`
if [ "$reroot" = "ufs:md0" ]; then

ZBOARD=`uname -i`
dd if=/tmp/flashpipe of=${UPGRADEDEV} obs=${UPGRADEBS} conv=osync &
echo "bin
get ${ZBOARD}.zimage /tmp/flashpipe
quit" | tftp ${UPGRADETFTP} 69

else
echo "not in md rootfs"
fi
else
echo "upgrade need ${CONF}"
fi

kill -INT 1
