#!/bin/sh

CONF="/etc/upgrade.conf"

if [ -e "${CONF}" ]; then

. ${CONF}

ping -c 3 ${UPGRADETFTP} >> /dev/null

if [ $? == 0 ]; then

echo -n "Flash upgrade ? [y/n] "

read ans

case $ans in
"y" | "Y" )

PIDFILE=`ls /var/run/*pid`
for p in ${PIDFILE} ; do
  kill `cat $p`
done

UNIDIR=`df | awk '/above/{print $6}'`
for u in ${UNIDIR} ; do
  umount $u
  if [ $? != 0 ]; then
    echo "can't umount $u"
    exit
  fi
done

if [ -z "${UPGRADEROOT}" ]; then
TMPDIR=`df | awk '$6=="/tmp"{print $1}'`
if [ "${TMPDIR}" = "tmpfs" ]; then
/sbin/mdconfig -a -t malloc -s 6m
newfs /dev/md0
mount /dev/md0 /mnt
NEXROOTFS="mnt"
else
NEXROOTFS="tmp"
fi
rm -rf /${NEXROOTFS}/*
mkdir /${NEXROOTFS}/dev
mkdir /${NEXROOTFS}/tmp
mkdir /${NEXROOTFS}/bin
mkdir /${NEXROOTFS}/sbin
mkdir /${NEXROOTFS}/libexec
mkdir /${NEXROOTFS}/lib
mkdir /${NEXROOTFS}/etc
mkdir /${NEXROOTFS}/usr
mkdir /${NEXROOTFS}/usr/bin
mkdir /${NEXROOTFS}/${NEXROOTFS}
cp /sbin/init /${NEXROOTFS}/sbin
cp /bin/sh /${NEXROOTFS}/bin
cp /libexec/ld-elf.so.1 /${NEXROOTFS}/libexec
cp /lib/libedit.so.7 /${NEXROOTFS}/lib
cp /lib/libc.so.7 /${NEXROOTFS}/lib
cp /lib/libncursesw.so.8 /${NEXROOTFS}/lib
cp /lib/libutil.so.9 /${NEXROOTFS}/lib
cp /bin/kill /${NEXROOTFS}/bin
cp /bin/dd /${NEXROOTFS}/bin
cp /bin/kenv /${NEXROOTFS}/bin
cp /usr/bin/tftp /${NEXROOTFS}/usr/bin
cp /usr/bin/uname /${NEXROOTFS}/usr/bin
cp ${CONF} /${NEXROOTFS}/etc
mkfifo /${NEXROOTFS}/tmp/flashpipe
cp /sbin/bupgrade /${NEXROOTFS}/etc/rc
df /${NEXROOTFS}
kenv vfs.root.mountfrom=ufs:md0
reboot -r

else
umount /tmp
if [ $? == 0 ]; then

dd if=${UPGRADEROOT} of=/dev/md0
if [ $? == 0 ]; then

# reroot setup
kenv vfs.root.mountfrom=cd9660:md0.uzip

reboot -r
else
echo "can't dd rootfs"
fi
else
fi
echo "can't umount /tmp"
fi
;;
esac

else
echo "${UPGRADETFTP} not alive"
fi

else
echo "upgrade need ${CONF}"
fi

