#!/bin/sh

stty status '^T'
trap : 2
trap "echo 'Boot interrupted'; exit 1" 3
HOME=/
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export HOME PATH

echo f1 > /dev/led/status

if [ "$1" = autoboot ]; then
	autoboot=yes
	_boot="faststart"
	rc_fast=yes
else
	autoboot=no
	_boot="quietstart"
fi
. /etc/rc.subr
load_rc_config 'XXX'
skip="-s nostart"
files=`rcorder ${skip} /etc/rc.d/* 2>/dev/null`
for _rc_elem in ${files}; do
	run_rc_script ${_rc_elem} ${_boot}
	case "$_rc_elem" in
	*/${early_late_divider})	break ;;
	esac
done
unset files local_rc
case ${local_startup} in
[Nn][Oo] | '') ;;
*)	find_local_scripts_new ;;
esac
files=`rcorder ${skip} /etc/rc.d/* ${local_rc} 2>/dev/null`
_skip_early=1
for _rc_elem in ${files}; do
	case "$_skip_early" in
	1)	case "$_rc_elem" in
		*/${early_late_divider})	_skip_early=0 ;;
		esac
		continue
		;;
	esac
	run_rc_script ${_rc_elem} ${_boot}
done
echo ''

date

echo f9 > /dev/led/status

exit 0
