#!/bin/sh
# PROVIDE: bridge
# REQUIRE: netif
# KEYWORD: nojail

. /etc/rc.subr
. /etc/network.subr

name="bridge"
start_cmd="bridge_start"
stop_cmd="bridge_stop"
cmd=""

glob_int () {
	case "$1" in
		$2 ) true ;;
		* ) false ;;
	esac
} 

bridge_test () {
	bridge=$1
	iface=$2

	eval interfaces=\$autobridge_${bridge}
	if [ -n "${interfaces}" ]; then
		for i in ${interfaces}; do
			if glob_int $iface $i ; then
				ifconfig $bridge $cmd $iface > /dev/null 2>&1
				return
			fi
		done
	fi
}

autobridge()
{
	if [ -n "${autobridge_interfaces}" ]; then
		if [ -z "$iflist" ]; then
			# We're operating as a general network start routine.
			iflist="`list_net_interfaces`"
		fi

		for br in ${autobridge_interfaces}; do
			for i in $iflist; do
				bridge_test $br $i
			done
		done
	fi
}

bridge_start()
{
	cmd="addm"
	autobridge
}

bridge_stop()
{
	cmd="deletem"
	autobridge
}

iflist=$2

load_rc_config $name
run_rc_command "$1"
