#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: cdevd
# REQUIRE: netif
# BEFORE: NETWORKING mountcritremote
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="cdevd"
rcvar=`set_rcvar`
command="/sbin/${name}"

load_rc_config $name
run_rc_command "$1"

# If cdevd is disabled, turn it off in the kernel to avoid memory leaks.
if ! checkyesno ${rcvar}; then
    sysctl hw.bus.devctl_disable=1
fi
