#!/bin/sh

# Start or stop racoon
# $FreeBSD: ports/security/ipsec-tools/files/racoon.sh.in,v 1.6 2009/07/15 16:56:02 dougb Exp $

# PROVIDE: racoon
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown

# Define these racoon_* variables in one of these files:
#	/etc/rc.conf
#	/etc/rc.conf.local
#	/etc/rc.conf.d/racoon
#
# DO NOT CHANGE THESE DEFAULT VALUES HERE
#
[ -z "$racoon_enable" ] && racoon_enable="NO"	# Disable by default
#racoon_flags=""				# Flags to racoon program
#racoon_create_dirs=YES				# Create $required_dirs (for
						#  /var mfs)?

. /etc/rc.subr

name="racoon"
rcvar=`set_rcvar`
command="/usr/bin/${name}"
pidfile="/var/run/${name}.pid"
socketfile="/var/run/${name}/${name}.sock"
required_files="/etc/${name}/${name}.conf"
required_dirs="/var/run/${name}"
start_precmd="racoon_cleanup"
stop_postcmd="racoon_cleanup"
start_cmd="${command} -f /etc/${name}/${name}.conf"

/bin/mkdir -p /var/run/racoon 

racoon_cleanup() {
	/bin/rm -f ${pidfile}
	/bin/rm -f ${socketfile}
	/usr/bin/setkey -f /etc/racoon/setkey.conf
}

load_rc_config $name
run_rc_command "$1"
