#!/bin/sh

# PROVIDE: resolv
# REQUIRE: netif
# KEYWORD: nojail

. /etc/rc.subr

name="resolv"
stop_cmd=':'

load_rc_config $name

# if the info is available via dhcp/kenv
# build the resolv.conf
#
if [ ! -e /etc/resolv.conf -a \
    -n "`/bin/kenv dhcp.domain-name-servers 2> /dev/null`" ]; then
	> /etc/resolv.conf

	if [ -n "`/bin/kenv dhcp.domain-name 2> /dev/null`" ]; then
		echo domain `/bin/kenv dhcp.domain-name` > /etc/resolv.conf
	fi

	set -- `/bin/kenv dhcp.domain-name-servers`
	for ns in `IFS=','; echo $*`; do
		echo nameserver $ns >> /etc/resolv.conf;
	done
fi

