#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/root,v 1.17.2.1.2.1 2009/10/25 01:10:29 kensmith Exp $
#

# PROVIDE: root
# KEYWORD: nojail

. /etc/rc.subr

name="root"
start_cmd="root_start"
stop_cmd=":"

root_start()
{
	# Export BDCFG to kenv
	for line in `/bin/cat /dev/map/bdcfg | /usr/bin/tail -c 8170 | /usr/bin/head -c 170 | /usr/bin/sed -E 's/^.{1,8}$//;'`; do
		kenv ${line}
	done
	/sbin/ifconfig bfe0 ether `kenv -q lanmac`
}

load_rc_config $name
run_rc_command "$1"
