#!/bin/sh

# PROVIDE: static_arp
# REQUIRE: netif
# KEYWORD: nojail

. /etc/rc.subr
. /etc/network.subr

name="static_arp"
start_cmd="static_arp_start"
stop_cmd="static_arp_stop"

static_arp_start()
{
	local e arp_args

	if [ -n "${static_arp_pairs}" ]; then
		echo -n 'Binding static ARP pair(s):'
		for e in ${static_arp_pairs}; do
			echo -n " ${e}"
			eval arp_args=\$static_arp_${e}
			arp -S ${arp_args} >/dev/null 2>&1
		done
		echo '.'
	fi
}

static_arp_stop()
{
	local e arp_args

	if [ -n "${static_arp_pairs}" ]; then
		echo -n 'Unbinding static ARP pair(s):'
		for e in ${static_arp_pairs}; do
			echo -n " ${e}"
			eval arp_args=\$static_arp_${e}
			arp -d ${arp_args%%[ 	]*} > /dev/null 2>&1
		done
		echo '.'
	fi
}

load_rc_config $name
run_rc_command "$1"
