# Something required by this vendor.

KERNCONF_NOOPTIONS+=			\
 	INVARIANTS			\
 	INVARIANT_SUPPORT		\
 	WITNESS				\
 	WITNESS_SKIPSPIN		\
 	DEBUG_REDZONE			\
 	DEBUG_MEMGUARD

KERNCONF_OPTIONS+=			\
 	SCSI_NO_SENSE_STRINGS		\
 	SCSI_NO_OP_STRINGS		\
        NO_SYSCTL_DESCR


