#!/bin/sh

# PROVIDE: ADAPTATION

. /etc/rc.subr
. /etc/network.subr

name="ADAPTATION"
start_cmd="adapt_start"
start_precmd="adapt_prestart"
start_postcmd="adapt_poststart"
stop_cmd="adapt_stop"

adapt_prestart()
{
	gpioctl -f /dev/gpioc0 -c 11 OUT
	gpioctl -f /dev/gpioc0 11 1

	# Import MAC addresses with known names
#	kenv LAN_MAC_ADDR=`kenv ethaddr`
#	kenv WAN_MAC_ADDR=`kenv wanmac`

#	ifconfig rt0 ether `kenv LAN_MAC_ADDR`
#	ifconfig rt0 up
#	ifconfig vlan1 create vlan 1 vlandev rt0
#	ifconfig vlan1 name lan0
#	ifconfig vlan2 create vlan 2 vlandev rt0
#	ifconfig vlan2 name wan0

#	ifconfig lan0 ether `kenv LAN_MAC_ADDR`
#	ifconfig wan0 ether `kenv WAN_MAC_ADDR`

	hostname `kenv HostName`

}

adapt_start()
{
}

adapt_poststart()
{
}

adapt_stop()
{
}

load_rc_config $name

run_rc_command $*
