#!/bin/sh

#
# mpd-linkup ng0 inet 95.81.35.177/32 195.128.182.55 - dns1 195.128.182.40 dns2 195.128.182.41 [12]
#

LOG=/tmp/mpd-linkup.log

touch ${LOG}
echo "mpd-linkup $*" >> ${LOG} 
#set >> ${LOG} 
echo >>  ${LOG}

interface=$1
proto=$2
localip=$3
remoteip=$4
authname=$5

case $# in
6)
	dns1="8.8.8.8"
	dns2="8.8.4.4"
	peeraddress=$6
	;;
7)
	dns1=$6
	dns2="8.8.8.8"
	peeraddress=$7
	;;
8)
	dns1=$6
	dns2=$7
	peeraddress=$8
	;;
esac

dns1=${dns1#dns1 }
dns2=${dns2#dns2 }

echo "MPD: iface=${interface} proto = ${proto} localip=${localip} remoteip=${remoteip} dns1=${dns1} dns2=${dns2} peeraddress=${peeraddress}" >> ${LOG}
query="cmd=event"
query="${query}&eventtype=linkup"
query="${query}&iface=${interface}"
query="${query}&proto=${proto}"
query="${query}&gw=${remoteip}"
query="${query}&ip=${localip}"
query="${query}&dns1=${dns1}"
query="${query}&dns2=${dns2}"

# Notify configuration handler
fetch -qo - "http://127.0.0.1:8/event.xml?${query}"

exit 0

