#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/sshd,v 1.14.2.1.2.1 2009/10/25 01:10:29 kensmith Exp $
#

# PROVIDE: shttpd
# REQUIRE: MAIN

. /etc/rc.subr


[ -z "$shttpd_enable" ] && shttpd_enable="YES"
[ -z "$shttpd_flags" ]  && shttpd_flags="-root /etc/www/ -ssi_ext shtml,html,js"

name="shttpd"
rcvar=`set_rcvar`
command="/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_cmd="shttpd_start"

shttpd_start()
{
	${command} ${shttpd_flags} &
}



load_rc_config $name
run_rc_command "$1"
