#!/bin/sh

#echo f1 > /dev/led/status
cd /tmp
echo "Dumping etc to etc.tar.gz"
/usr/bin/tar cv --exclude '*pwd.db' -zf /tmp/etc.tar.gz etc/* -C /tmp

lsline=`ls -l /tmp/etc.tar.gz`
script="arg5() echo \$5; arg5 ${lsline}"
size=`sh -c "${script}"`
if [ ${size} -gt 65536 ]; then
	echo "etc.tar.gz too big ${size}, must be less than 65536"
	echo "Please remove big files from /etc"
	exit 1
fi 

echo "Saving /etc"
sysctl hw.cfi.rdonly=0
/bin/dd if=/tmp/etc.tar.gz of=/dev/map/config bs=64k count=1 conv=sync
echo '.'

#echo f9 > /dev/led/status
