#!/bin/sh

# XXX: Should be in some plase like /etc/rc.conf
# D-Link_DIR-620-0.1-ALPHA.9ced6c669eb1da9e67c0fd2024058159.zimage
VENDOR=D-Link
#HWNAME=DIR-620_A1
HWNAME=DIR-620
CURRENT_VERSION=0.1
CURRENT_RELEASE=ALPHA

URL=$1
DEVICE=/dev/map/upgrade
FWFILE=/tmp/fw.img
BLOCK_SIZE=64
GEOM_PART=`echo ${DEVICE} | sed 's/\/dev\///; s!\/!\\\/!' `

i=0
for s in `sysctl kern.geom.conftxt | grep "${GEOM_PART}"` ; do
        i=$(( ${i} + 1 )) ;
        if [ ${i} == 4 ] ; then
                DEVICESIZE=${s} ;
        fi ;
done

DEVICEBLKS=$((${DEVICESIZE} / ${BLOCK_SIZE} / 1024))

#echo f1 > /dev/led/status

for p in collector.sh.pid collector.pid dhcpd.pid hostapd.pid httpd.sh.pid httpd.pid ; do
    echo "Kill ${p}"
    kill `cat /var/run/${p}` > /dev/null 2>&1
    # XXX: collector and httpd can't remove thier pid's (yet)
    rm -f /var/run/${p}
done


cd /tmp
rm -f ${FWFILE}
echo "Fetching new image from $1"
fetch -o ${FWFILE} "$1" || exit 1

lsline=`ls -l ${FWFILE}`
script="arg5() echo \$5; arg5 ${lsline}"
size=`sh -c "${script}"`
if [ ${size} -gt ${DEVICESIZE} ]; then
        echo "new image too big ${size}, must be less than ${DEVICESIZE}"
        exit 1
fi

# TODO: image check here
SRCMD5=`echo "$1" | sed -E "s/^${VENDOR}\_${HWNAME}\-[[:digit:]]+\.[[:digit:]]+\-[[:alnum:]]+\.//; s/\.zimage$//"`
arg4() echo $4; MD5=`arg4 \`md5 ${FWFILE}\``;

if [ "${SRCMD5}" != "${MD5}" ]; then
	echo "Checksum mismatch, upgrade aborted";
	# XXX: Better to restore services
	reboot;
fi

# XXX: readonly for now
sysctl hw.cfi.rdonly=0

killall mpd
for p in dhclient.pid mpd.pid ; do
    echo "Kill ${p}"
    kill `cat /var/run/${p}` > /dev/null 2>&1
    # XXX: collector and httpd can't remove thier pid's (yet)
    rm -f /var/run/${p}
done
echo "Update /dev/md0 mount to sync mode"
mount -u -o sync /dev/md0 /tmp
echo "Flashing new Firware image"
# -V don't verify, -S don't sync
upgrade -f ${FWFILE} -S -d ${DEVICE}
echo '.'

#echo f9 > /dev/led/status

