#!/bin/sh

URL=$1
DEVICE=/dev/map/upgrade
FWFILE=/tmp/fw.img
BLOCK_SIZE=64
GEOM_PART=`echo ${DEVICE} | sed 's/\/dev\///; s!\/!\\\/!' `

i=0
for s in `sysctl kern.geom.conftxt | grep "${GEOM_PART}"` ; do
        i=$(( ${i} + 1 )) ;
        if [ ${i} == 4 ] ; then
                DEVICESIZE=${s} ;
        fi ;
done

DEVICEBLKS=$((${DEVICESIZE} / ${BLOCK_SIZE} / 1024))

#echo f1 > /dev/led/status

for p in collector.sh.pid collector.pid dhcpd.pid hostapd.pid httpd.sh.pid httpd.pid ; do
    echo "Kill ${p}"
    kill `cat /var/run/${p}` 2&>1 > /dev/null
    # XXX: collector and httpd can't remove thier pid's (yet)
    rm -f /var/run/${p}
done


cd /tmp
rm -f ${FWFILE}
echo "Fetching new image from "
fetch -o ${FWFILE} "$1" || exit 1

lsline=`ls -l ${FWFILE}`
script="arg5() echo \$5; arg5 ${lsline}"
size=`sh -c "${script}"`
if [ ${size} -gt ${DEVICESIZE} ]; then
        echo "new image too big ${size}, must be less than ${DEVICESIZE}"
        exit 1
fi

# TODO: image check here

# XXX: readonly for now
sysctl hw.cfi.rdonly=0

killall mpd
for p in dhclient.pid mpd.pid ; do
    echo "Kill ${p}"
    kill `cat /var/run/${p}` 2&>1 > /dev/null
    # XXX: collector and httpd can't remove thier pid's (yet)
    rm -f /var/run/${p}
done
echo "Update /dev/md0 mount to sync mode"
mount -u -o sync /dev/md0 /tmp
echo "Flashing new Firware image"
# -V don't verify, -S don't sync
upgrade -f ${FWFILE} -S -d ${DEVICE}
echo '.'

#echo f9 > /dev/led/status

