#!/bin/sh

URL=$1
DEVICE=/dev/map/upgrade
BLOCK_SIZE=64
GEOM_PART=`echo ${DEVICE} | sed 's/\/dev\///; s!\/!\\\/!' `

i=0
for s in `sysctl kern.geom.conftxt | grep "${GEOM_PART}"` ; do
	i=$(( ${i} + 1 )) ;
	if [ ${i} == 4 ] ; then
    		DEVICESIZE=${s} ;
	fi ;
done

DEVICEBLKS=$((${DEVICESIZE} / ${BLOCK_SIZE} / 1024))

#echo f1 > /dev/led/status
cd /tmp
echo "Fetching new image from "
fetch -o /tmp/fw.img "$1" || exit 1

lsline=`ls -l /tmp/fw.img`
script="arg5() echo \$5; arg5 ${lsline}"
size=`sh -c "${script}"`
if [ ${size} -gt ${DEVICESIZE} ]; then
	echo "new image too big ${size}, must be less than ${DEVICESIZE}"
	exit 1
fi 

echo "Flashing new Firware image"
#sysctl hw.cfi.rdonly=0
/bin/dd if=/tmp/fw.img of=${DEVICE} bs=${BLOCK_SIZE}k count=${DEVICEBLKS} conv=sync
echo '.'

#echo f9 > /dev/led/status
