CONVERT_FROM_CRAMFS:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_CRAMFS:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_CRAMFS?=mkcramfs

${CONVERT_TO_CRAMFS}:		${CONVERT_FROM_CRAMFS}
	@echo ========== Convert ${CONVERT_FROM_CRAMFS} to ${CONVERT_TO_CRAMFS} with ${CONVERTER_CRAMFS} ============
	rm -f ${CONVERT_TO_CRAMFS}
	rm -rf ${CONVERT_FROM_CRAMFS}_kernelfs
	mkdir ${CONVERT_FROM_CRAMFS}_kernelfs
	cp ${CONVERT_FROM_CRAMFS} ${CONVERT_FROM_CRAMFS}_kernelfs/kernel.kbin
	${CONVERTER_CRAMFS} ${CONVERT_FROM_CRAMFS}_kernelfs ${CONVERT_TO_CRAMFS}
