CONVERT_FROM_GZ:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_GZ:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_GZ?=gzip
CONVERTER_GZ_FLAGS?=--stdout

${CONVERT_TO_GZ}:		${CONVERT_FROM_GZ}
	@echo ========== Convert ${CONVERT_FROM_GZ} to ${CONVERT_TO_GZ} with ${CONVERTER_GZ} ============
	${CONVERTER_GZ} ${CONVERTER_GZ_FLAGS} ${CONVERT_FROM_GZ} > ${CONVERT_TO_GZ}
