CONVERT_FROM_KBIN:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_KBIN:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_KBIN?=objcopy
CONVERTER_KBIN_FLAGS?=-O binary

${CONVERT_TO_KBIN}:		${CONVERT_FROM_KBIN}
	@echo ========== Convert ${CONVERT_FROM_KBIN} to ${CONVERT_TO_KBIN} with ${CONVERTER_KBIN} ============
	rm -f ${CONVERT_TO_KBIN}
	PATH=${IMAGE_BUILD_PATHS} ${CONVERTER_KBIN} ${CONVERTER_KBIN_FLAGS} ${CONVERT_FROM_KBIN} ${CONVERT_TO_KBIN}
