CONVERT_FROM_OLDLZMA:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_OLDLZMA:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_OLDLZMA?=oldlzma
CONVERTER_OLDLZMA_FLAGS?=e

${CONVERT_TO_OLDLZMA}:		${CONVERT_FROM_OLDLZMA}	${ZTOOLS_PATH}/oldlzma
	@echo ========== Convert ${CONVERT_FROM_OLDLZMA} to ${CONVERT_TO_OLDLZMA} with ${CONVERTER_OLDLZMA} ============
	PATH=${IMAGE_BUILD_PATHS} ${CONVERTER_OLDLZMA} ${CONVERTER_OLDLZMA_FLAGS} ${CONVERT_FROM_OLDLZMA} ${CONVERT_TO_OLDLZMA}
