CONVERT_FROM_ULZMA:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_ULZMA:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_ULZMA?=mkulzma
CONVERTER_ULZMA_FLAGS?=${MKULZMA_FLAGS} -s ${MKULZMA_BLOCKSIZE}

${CONVERT_TO_ULZMA}:		${CONVERT_FROM_ULZMA} ${ZTOOLS_PATH}/mkulzma
	@echo ========== Convert ${CONVERT_FROM_ULZMA} to ${CONVERT_TO_ULZMA} with ${CONVERTER_ULZMA} ============
	PATH=${IMAGE_BUILD_PATHS} ${CONVERTER_ULZMA} ${CONVERTER_ULZMA_FLAGS} -o ${CONVERT_TO_ULZMA} ${CONVERT_FROM_ULZMA}
