CONVERT_FROM_UZIP:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_UZIP:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_UZIP?=mkuzip
CONVERTER_UZIP_FLAGS?=${MKUZIP_FLAGS} -s ${MKUZIP_BLOCKSIZE}

${CONVERT_TO_UZIP}:		${CONVERT_FROM_UZIP} ${ZTOOLS_PATH}/${CONVERTER_UZIP}
	@echo ========== Convert ${CONVERT_FROM_UZIP} to ${CONVERT_TO_UZIP} with ${CONVERTER_UZIP} ============
	PATH=${IMAGE_BUILD_PATHS} ${CONVERTER_UZIP} ${CONVERTER_UZIP_FLAGS} -o ${CONVERT_TO_UZIP} ${CONVERT_FROM_UZIP}
