CONVERT_FROM_UZIP:=${NEW_CURRENT_PACKING_FILE_NAME}
CONVERT_TO_UZIP:=${CURRENT_PACKING_FILE_NAME}

# Let user to override
CONVERTER_UZIP?=mkuzip
CONVERTER_UZIP_FLAGS?=${MKUZIP_FLAGS} -s ${MKUZIP_BLOCKSIZE}

.if ${USE_SYSTEMTOOLS} == "yes"
_CONV_DEPEND=${CONVERT_FROM_UZIP}
.else
_CONV_DEPEND=${CONVERT_FROM_UZIP} ${ZTOOLS_PATH}/mkuzip
.endif

${CONVERT_TO_UZIP}:		${_CONV_DEPEND}
	@echo ========== Convert ${CONVERT_FROM_UZIP} to ${CONVERT_TO_UZIP} with ${CONVERTER_UZIP} ============
	PATH=${IMAGE_BUILD_PATHS} ${CONVERTER_UZIP} ${CONVERTER_UZIP_FLAGS} -o ${CONVERT_TO_UZIP} ${CONVERT_FROM_UZIP}
