

SOC_VENDOR=Broadcom
SOC_CHIP=BCM5354
KERNEL_COMPRESSION=lzma.4.17

KERNCONF_IDENT=${TARGET_VENDOR}_${TARGET_DEVICE}

WITH_USB=yes
KERNCONF_MAKEOPTIONS+=	"MODULES_OVERRIDE=\"ipfw usb/umass usb/uplcom usb/u3g\""
