#!/bin/sh

# PROVIDE: ADAPTATION

. /etc/rc.subr
. /etc/network.subr

name="ADAPTATION"
start_cmd="adapt_start"
start_precmd="adapt_prestart"
start_postcmd="adapt_poststart"
stop_cmd="adapt_stop"

adapt_prestart()
{
ENVDEV="/dev/cfid0s.factory"

	kenvmac=`kenv -q LAN_MAC_ADDR`
	if [ -z "$kenvmac" ]; then

		# Import MAC addresses from flash
		kenv LAN_MAC_ADDR=`od -t x1 ${ENVDEV} | awk '/^0000000/{print $6":"$7":"$8":"$9":"$10":"$11}'`

		ifconfig rt0 ether `kenv LAN_MAC_ADDR`

		etherswitchcfg -f /dev/etherswitch1 port0 pvid 1
		etherswitchcfg -f /dev/etherswitch1 vlangroup0 members 0,1,2,3,4,5

		hostname `kenv HostName`

	fi

}

adapt_start()
{
}

adapt_poststart()
{
}

adapt_stop()
{
}

load_rc_config $name

run_rc_command $*
