#!/bin/sh

# PROVIDE: mountcritlocal

. /etc/rc.subr
. /etc/network.subr

name="MAIN"
start_cmd="mountcritlocal_start"

mountcritlocal_start()
{
	# XXX: check TMPFS again
	# XXX: get useful size: small for /etc or big for upgrade
	md=`/sbin/mdconfig -a -t malloc -s 10m`
	newfs -b 4096 -f 512 -n -o space /dev/${md} > /dev/null
	mount /dev/${md} /tmp

	mkdir -p /tmp/etc
	mkdir -p /tmp/var/empty
	mkdir -p /tmp/var/log
	mkdir -p /tmp/var/run
	mkdir -p /tmp/var/spool/lock
	touch /tmp/var/log/all.log

	mount_unionfs /tmp/etc /etc

	if [ -c /dev/map/config ]; then
		dd if=/dev/map/config of=/tmp/etc.tar.gz;
		cd /tmp/ && tar xvzf /tmp/etc.tar.gz
	else
		if [ -c /dev/redboot/config ]; then
			dd if=/dev/redboot/config of=/tmp/etc.tar.gz;
			cd /tmp/ && tar xvzf /tmp/etc.tar.gz
		fi
	fi

}

load_rc_config $name

run_rc_command $*