#!/bin/sh

# PROVIDE: NETWORKING
# REQUIRE: serial sysctl
# KEYWORD: nojail

. /etc/rc.subr
. /etc/network.subr

name="network"
start_cmd="network_start"
stop_cmd="network_stop"
cloneup_cmd="clone_up"
clonedown_cmd="clone_down"
extra_commands="cloneup clonedown"
cmdifn=

set_rcvar_obsolete ipv6_enable ipv6_activate_all_interfaces
set_rcvar_obsolete ipv6_prefer

network_start()
{
	# Set the list of interfaces to work on.
	#
	cmdifn=$*

	if [ -z "$cmdifn" ]; then
		#
		# We're operating as a general network start routine.
		#

		# disable SIGINT (Ctrl-c) when running at startup
		trap : 2

		# Create cloned interfaces
		clone_up

		# Create Fast EtherChannel interfaces
		fec_up

		# Create IPv6<-->IPv4 tunnels
		gif_up

		# Rename interfaces.
		ifnet_rename
	fi

	# Configure the interface(s).
	network_common ifn_start

	if [ -f /etc/rc.d/ipfilter ] ; then
		# Resync ipfilter
		/etc/rc.d/ipfilter quietresync
	fi
	if [ -f /etc/rc.d/bridge -a -n "$cmdifn" ] ; then
		/etc/rc.d/bridge start $cmdifn
	fi
}

network_stop()
{
	# Set the list of interfaces to work on.
	#
	cmdifn=$*

	# Deconfigure the interface(s)
	network_common ifn_stop
}

# network_common routine
#	Common configuration subroutine for network interfaces. This
#	routine takes all the preparatory steps needed for configuriing
#	an interface and then calls $routine.
network_common()
{
	local _cooked_list _fail _func _ok _str

	_func=

	if [ -z "$1" ]; then
		err 1 "network_common(): No function name specified."
	else
		_func="$1"
	fi

	# Set the scope of the command (all interfaces or just one).
	#
	_cooked_list=
	if [ -n "$cmdifn" ]; then
		# Don't check that the interface(s) exist.  We need to run
		# the down code even when the interface doesn't exist to
		# kill off wpa_supplicant.
		# XXXBED: is this really true or does wpa_supplicant die?
		# if so, we should get rid of the devd entry
		_cooked_list="$cmdifn"
	else
		_cooked_list="`list_net_interfaces`"
	fi

	_fail=
	_ok=
	for ifn in ${_cooked_list}; do
		if ${_func} ${ifn} $2; then
			_ok="${_ok} ${ifn}"
		else
			_fail="${_fail} ${ifn}"
		fi
	done

	_str=
	if [ -n "${_ok}" ]; then
		case ${_func} in
		ifn_start)
			_str='Starting'
			;;
		ifn_stop)
			_str='Stopping'
			;;
		esac
		echo "${_str} Network:${_ok}."
		if check_startmsgs; then
			for ifn in ${_ok}; do
				/sbin/ifconfig ${ifn}
			done
		fi
	fi

	debug "The following interfaces were not configured: $_fail"
}

load_rc_config $name
run_rc_command $*
