#!/bin/sh

# PROVIDE: tmp

. /etc/rc.subr

name="tmp"
stop_cmd=':'

load_rc_config $name

if _tmpdir=$(mktemp -d -q /tmp/.diskless.XXXXXX); then
	rmdir ${_tmpdir}
else
	if [ -h /tmp ]; then
		echo "*** /tmp is a symlink to a non-writable area!"
		echo "dropping into shell, ^D to continue anyway."
		/bin/sh
	else
		mount_md ${tmpsize} /tmp "${tmpmfs_flags}"
		chmod 01777 /tmp
	fi
fi
