# Atheros AR9331 support profile.

TARGET=			mips
TARGET_ARCH=		mips

KERNCONF_MACHINE=	${TARGET} ${TARGET_ARCH}
KERNCONF_IDENT?=	AR9331
KERNCONF_CPU=		CPU_MIPS4KC
KERNCONF_FILES+=	"../atheros/files.ar71xx"

KERNCONF_KERNLOADADDR?=		0x80050000
KERNCONF_OPTIONS+=		ALQ
KERNCONF_OPTIONS+=		HZ=1000
KERNCONF_OPTIONS+=		MAXUSERS=3
KERNCONF_OPTIONS+=		MAXFILES=512
KERNCONF_OPTIONS+=		SHMALL=128
KERNCONF_OPTIONS+=		MSGBUF_SIZE=65536

# Options for making kernel smallest 
KERNCONF_OPTIONS+=		NO_SYSCTL_DESCR		# No description string of sysctl
KERNCONF_OPTIONS+=		NO_FFS_SNAPSHOT		# Disable Snapshot supporting
KERNCONF_OPTIONS+=		SCSI_NO_SENSE_STRINGS
KERNCONF_OPTIONS+=		SCSI_NO_OP_STRINGS

# Board definitions
KERNCONF_OPTIONS+=	INET
KERNCONF_OPTIONS+= 	TMPFS
KERNCONF_OPTIONS+= 	CD9660
KERNCONF_DEVICES+=	geom_uzip

# Project definitions
KERNCONF_OPTIONS+=	SCHED_4BSD
KERNCONF_OPTIONS+=	PSEUDOFS
KERNCONF_OPTIONS+=	_KPOSIX_PRIORITY_SCHEDULING

KERNCONF_DEVICES+=	uart
KERNCONF_DEVICES+=	uart_ar933x
KERNCONF_DEVICES+=	random
KERNCONF_DEVICES+=	loop
KERNCONF_DEVICES+=	ether
KERNCONF_DEVICES+= 	tun
KERNCONF_DEVICES+= 	pty
KERNCONF_DEVICES+= 	bpf
KERNCONF_DEVICES+=	vlan

KERNCONF_DEVICES+=	mii
KERNCONF_DEVICES+=	arge

KERNCONF_DEVICES+=	gpio

KERNCONF_DEVICES+=	mx25l
KERNCONF_DEVICES+=	spibus
KERNCONF_DEVICES+=	ar71xx_spi
KERNCONF_DEVICES+=	ar71xx_wdog
KERNCONF_DEVICES+=	ar71xx_apb


.if defined(WITH_IPSEC)
KERNCONF_OPTIONS+=      IPSEC
KERNCONF_OPTIONS+=      IPSEC_NAT_T

KERNCONF_DEVICES+=	enc
KERNCONF_DEVICES+=	ipsec
KERNCONF_DEVICES+=	crypto
.endif

.if !defined(WITHOUT_WIRELESS) && !defined(WITH_WIRELESS_MODULES)
# Wireless NIC cards
KERNCONF_OPTIONS+=      IEEE80211_SUPPORT_MESH
KERNCONF_OPTIONS+=      IEEE80211_SUPPORT_TDMA
KERNCONF_OPTIONS+=      IEEE80211_SUPPORT_SUPERG
KERNCONF_DEVICES+=	wlan            # 802.11 support
KERNCONF_DEVICES+=	wlan_wep        # 802.11 WEP support
KERNCONF_DEVICES+=	wlan_ccmp       # 802.11 CCMP support
KERNCONF_DEVICES+=	wlan_tkip       # 802.11 TKIP support
KERNCONF_DEVICES+=	wlan_xauth	# 802.11 hostap support

# ath(4)
KERNCONF_DEVICES+=	ath             # Atheros network device
KERNCONF_DEVICES+=	ath_rate_sample
KERNCONF_DEVICES+=	ath_ahb		# Atheros host bus glue
KERNCONF_OPTIONS+=      ATH_ENABLE_11N
KERNCONF_DEVICES+=	ath_ar9300		# AR9330 HAL; no need for the others
KERNCONF_OPTIONS+=      AH_SUPPORT_AR5416	# 11n HAL support
KERNCONF_OPTIONS+=      AH_SUPPORT_AR9330	# Chipset support
KERNCONF_OPTIONS+=      AH_AR5416_INTERRUPT_MITIGATION
.endif

.if defined(WITH_USB)
KERNCONF_OPTIONS+=	USB_EHCI_BIG_ENDIAN_DESC
KERNCONF_OPTIONS+=	USB_HOST_ALIGN=32

KERNCONF_DEVICES+=	usb
KERNCONF_DEVICES+=	ehci

KERNCONF_DEVICES+=	umass

# SCSI peripherals
KERNCONF_DEVICES+=     scbus
KERNCONF_DEVICES+=     da
.endif
