# TOOLS_SUBDIRS not cleaned to allow user prepend
.include <bsd.own.mk>

SUBDIR+= \
	config \
	make_dlink_dsr_image \
	mktplinkfw \
	oldlzma \
	packimage \
	trx \
	ubnt-mkfwimage \
	uboot_mkimage

.include <bsd.subdir.mk>
