#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/hostapd,v 1.3.2.1.2.1 2009/10/25 01:10:29 kensmith Exp $
#

# PROVIDE: hostapd
# REQUIRE: MAIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

#[ -z "${hostapd_enable}" ] && hostapd_enable="YES"
hostapd_enable="YES"
name="hostapd"
command="/usr/sbin/${name}"
rcvar=`set_rcvar`

conf_file="/etc/${name}.conf"
pidfile="/var/run/${name}.pid"

command_args="-P ${pidfile} -B ${conf_file}"
required_files="${conf_file}"
required_modules="wlan_xauth wlan_wep wlan_tkip wlan_ccmp"
extra_commands="reload"

load_rc_config ${name}
run_rc_command "$1"
