#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/wpa_supplicant,v 1.6.2.2.2.1 2009/10/25 01:10:29 kensmith Exp $
#

# PROVIDE: wpa_supplicant
# REQUIRE: MAIN
# KEYWORD: nojail nostart

. /etc/rc.subr
. /etc/network.subr

name="wpa_supplicant"
rcvar=

ifn="$2"
if [ -z "$ifn" ]; then
	return 1
fi

if is_wired_interface ${ifn} ; then
	driver="wired"
else
	driver="bsd"
fi

load_rc_config $name

command=${wpa_supplicant_program}
conf_file=${wpa_supplicant_conf_file}
pidfile="/var/run/${name}/${ifn}.pid"
command_args="-B -i $ifn -c $conf_file -D $driver -P $pidfile"
required_files=$conf_file
required_modules="wlan_wep wlan_tkip wlan_ccmp"

run_rc_command "$1"
