#!/bin/sh

# PROVIDE: ADAPTATION

. /etc/rc.subr
. /etc/network.subr

name="ADAPTATION"
start_cmd="adapt_start"
start_precmd="adapt_prestart"
start_postcmd="adapt_poststart"
stop_cmd="adapt_stop"

adapt_prestart()
{
#	switchctl /dev/switch0 set vlan 0 vid 1
#	switchctl /dev/switch0 set vlan 0 add 0 u
#	switchctl /dev/switch0 set vlan 0 add 1 u
#	switchctl /dev/switch0 set vlan 0 add 2 u
#	switchctl /dev/switch0 set vlan 0 add 3 u
#	switchctl /dev/switch0 set vlan 0 del 4
#	switchctl /dev/switch0 set vlan 0 add 5 t
#	switchctl /dev/switch0 set vlan 0 add 6 t
#
#	switchctl /dev/switch0 set vlan 1 vid 2
#	switchctl /dev/switch0 set vlan 1 del 0
#	switchctl /dev/switch0 set vlan 1 del 1
#	switchctl /dev/switch0 set vlan 1 del 2
#	switchctl /dev/switch0 set vlan 1 del 3
#	switchctl /dev/switch0 set vlan 1 add 4 u
#	switchctl /dev/switch0 set vlan 1 add 5 t
#	switchctl /dev/switch0 set vlan 1 add 6 t
#
#	switchctl /dev/switch0 set port 0 pvid 1 flags Untag
#	switchctl /dev/switch0 set port 1 pvid 1 flags Untag
#	switchctl /dev/switch0 set port 2 pvid 1 flags Untag
#	switchctl /dev/switch0 set port 3 pvid 1 flags Untag
#	switchctl /dev/switch0 set port 4 pvid 2 flags Untag
#
#	switchctl /dev/switch0 set port 5 pvid 1 flags Tag
#	switchctl /dev/switch0 set port 6 pvid 1 flags Tag

	RESET_PIN=$(kenv RESET_PIN)
	WPS_PIN=$(kenv WPS_PIN)
	gpioctl -f /dev/gpioc0 -c ${RESET_PIN} IN II INT
	gpioctl -f /dev/gpioc0 -c ${WPS_PIN} IN II INT

	# Import MAC addresses with known names
#	kenv LAN_MAC_ADDR=`kenv ethaddr`
#	kenv WAN_MAC_ADDR=`kenv wanmac`

	ifconfig arge0 name lan0
	ifconfig arge1 name wan0
	ifconfig ath0 name wifi0

	ifconfig lan0 ether `kenv LAN_MAC_ADDR`
	ifconfig wan0 ether `kenv WAN_MAC_ADDR`
#	ifconfig wifi0 ether `kenv WLAN_MAC_ADDR`

	# Enable Wireless LED
	sysctl dev.ath.0.ledpin=1
	sysctl dev.ath.0.softled=0
	sysctl dev.ath.0.softled=1
	sysctl dev.ath.0.ledpin=0
	sysctl dev.ath.0.softled=0
	sysctl dev.ath.0.softled=1

	# Preset "Internet" LED to black
	echo 0 > /dev/led/internet
	echo 1 > /dev/led/internet_bi

	hostname `kenv HostName`

}

adapt_start()
{
}

adapt_poststart()
{
}

adapt_stop()
{
}

load_rc_config $name

run_rc_command $*